services:
  backend:
    networks:
      - coolify
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend-flow.rule=Host(`backendflow.hecainnova.work`)'
      # Cambiamos 'websecure' por 'https'
      - 'traefik.http.routers.backend-flow.entrypoints=https'
      # Cambiamos 'myresolver' por 'letsencrypt'
      - 'traefik.http.routers.backend-flow.tls.certresolver=letsencrypt'
      - 'traefik.http.services.backend-flow.loadbalancer.server.port=3001'
    ports:
      - '127.0.0.1:${PORT:-3001}:${PORT:-3001}'
    env_file:
      - .env

networks:
  coolify:
    external: true
